### ISSUE TITLE
Integer wraparound causes huge output for tiny DMS files

### ISSUE THREAD

**Issue by sagamusix** [temisu/ancient#12]
The attached file is tiny and has a valid DMS header, yet it produces a 4GB output due to an integer wraparound in `_rawSize=(numTracks-minTrack)*trackSize+lastTrackSize;` which happens if `numTracks < 80`.

[huge.zip](https://github.com/temisu/ancient/files/6064016/huge.zip)

**Comment by temisu** [comment]
Good catch.

I think I'm going to "steal" the idea of the overflow check and put it into the code as well...

**Comment by temisu** [comment]
Ok, I stole your approach for overflow checking and added it to the code - although the DMS-problem was a different one than pure overflow. Now the code should be fine on 32-bit systems as well
