### ISSUE TITLE
warning in main.cpp with GCC 9 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by manxorist** [temisu/ancient#27]
```
main.cpp: In lambda function:
main.cpp:182:45: warning: ignoring attributes on template argument ‘int (*)(DIR*)’ {aka ‘int (*)(__dirstream*)’} [-Wignored-attributes]
  182 |    std::unique_ptr<DIR,decltype(&::closedir)> dir{::opendir(inputDir.c_str()),::closedir};
      |                                             ^
```
I guess it warns because in `<dirent.h>`, `closedir` is declared as `extern int closedir (DIR *__dirp) __nonnull ((1));` with `__nonnull` being `# define __nonnull(params) __attribute__ ((__nonnull__ params))`.

Not sure how to fix that, short of just ignoring the warning.

Directory walking could also be rewritten with `std::filesystem` (if available on all platforms that ancient cares about).

I do not consider this high priority at all, though.

**Comment by temisu** [comment]
Well, that was frustrating to fix, but fixed (I did not want to install ubuntu just for this)
