### ISSUE TITLE
Version number confusion between release version and autotools version

### ISSUE THREAD

**Issue by manxorist** [temisu/ancient#37]
When I contributed the Autotools build system in https://github.com/temisu/ancient/pull/21, I noted that I added version information to `configure.ac`:
> Introduce package versioning (using SemVer) and soname versioning via libtool.
> Details are documented at the top of configure.ac.

As the updated API which is incompatible with the older ad-hoc API also went in, I did set the version to 2.0.0-pre, as required by SemVer.

Yet, the update to ancient as a whole you recently released has version 1.1, and the Autotools build system still advertises a pre-release package version 2.0.0-pre.2.

This likely confuses users. I suggest these versions should match and ancient should follow the versioning guidelines that I did add at the top of `configure.ac`.

Setting the Autotools package version to 2.0.0, and releasing a release versioned also 2.0.0 in a timely fashion should cleanup the situation for now, I think.

I am sorry if I might have caused confusion about the intentions that my versioning changes implied, and I maybe did not communicate the changes properly.

**Comment by temisu** [comment]
I'll try to see tonight if that helps - we can always remove the version if it does not

**Comment by temisu** [comment]
Yeah, I'm no expert on debian builds either and I kind of missed that comment about versions, lets see if this helps

**Comment by manxorist** [comment]
Thanks, The release looks good to me now. Can you also increment LIBANCIENT_LTVER_REVISION (https://github.com/temisu/ancient/blob/master/configure.ac#L20) now, after the release?

**Comment by temisu** [comment]
oops, missed that

**Comment by temisu** [comment]
Looks it is all good now. Closing. Re-open if there are any further issues
