### ISSUE TITLE
Surprising increase in distfile size in 2.1.0

### ISSUE THREAD

**Issue by ryandesign** [temisu/ancient#44]
The GitHub generated tarball of ancient 2.0.0 was 102KB. The tarball of ancient 2.1.0 is 15.7MB. This increase is surprising. I think most/all of this is coming from the new `testing` directory. Is this directory required to build/install ancient? I tried deleting it and `./configure` and `make` and `make install` worked fine.

**Comment by ryandesign** [comment]
How would you feel about offering an official distribution tarball for each version? It could exclude nonessential files like this testing directory, and include files like those generated by `./autogen.sh`. You could attach this tarball to the GitHub release.

**Comment by temisu** [comment]
I’ll look into it - I anyway need to do a fixup release because of visual studio warnings.

**Comment by temisu** [comment]
Please check if the distfile is now reasonable - I had to debug it remotely (since I have problems running autotools locally). According to logs it is doing the right thing.

Acount the generated files - this has to wait a bit more

**Comment by ryandesign** [comment]
> Please check if the distfile is now reasonable

Indeed the tarball for 2.1.1 is only 117,915 bytes and for 2.2.0 it's only 119,589 bytes.
