### ISSUE TITLE
Vice/Vic2

### ISSUE THREAD

**Issue by peter20051** [temisu/ancient#54]
Any plan for supporting this type of crunched files in the future release?

**Comment by temisu** [comment]
I did not have success finding vic2 in vice emulator (apart from vic-20 and vic II but those are not related to file formats, at least I did not find anything). Google thinks vic II refers to "Victoria II"-game, which apparently has compressed and uncompressed save games but thats about it.

So I have to admit I don't know what file format you are referring here. Can you help with some reference?

**Comment by peter20051** [comment]
references here 
https://aminet.net/package/util/pack/xfdmaster
https://eab.abime.net/showthread.php?t=56502&highlight=vic2


Although it's not clear to me if it is compression and/or protection.

**Comment by temisu** [comment]
Ok, some old format that is supported by xfdmaster even.

That should be doable. But I need to investigate
