### ISSUE TITLE
Another format that takes really long to unpack (found via fuzzing)

### ISSUE THREAD

**Issue by sagamusix** [temisu/ancient#63]
Here's another troublesome file... just 113 bytes, but it takes 1.5 minutes here until ancient is done processing it. Unlike #60, I think this one is not encrypted (the call stack shows it is handled by `CompressDecompressor`). Maybe this one can be improved as well?

[id%3A000009,time%3A0,execs%3A0,orig%3Aid%3A002214,sync%3Afuzzer01,src%3A002196.zip](https://github.com/temisu/ancient/files/14628489/id.3A000009.time.3A0.execs.3A0.orig.3Aid.3A002214.sync.3Afuzzer01.src.3A002196.zip)

**Comment by temisu** [comment]
It is essentially an accidental decompression-bomb. (decompressed size before failure was around 1G) I'll add max-checking and while at it, I'll see where else it is missing

**Comment by sagamusix** [comment]
Looks good, both files fail very quickly now :)
