### ISSUE TITLE
PMC. format request

### ISSUE THREAD

**Issue by Kaens** [temisu/ancient#68]
Hi,
I've stumbled upon a couple of tracker music files compressed by PowerPlayer Music Cruncher, a proprietary thing apparently employing lh.library. Then I noticed "LHLB" compression also depends on the library. Since you have XPK-LHLB, I thought it'd be trivial for you to adapt it to unpack them (although I couldn't find any other open project that can).
[Here they are.](https://github.com/temisu/ancient/files/14849001/med-to-pmc-samples.zip) I strongly suspect they're files whose unpacked versions start with "MMD1" (or MMD2 at least). The beginning of the format is like this: uint32be fourcc, uint32 rawsz, uint32 filesz-12 (the entire header would be 12 bytes long).

**Comment by temisu** [comment]
Hi,

Thanks for the pointers. I'll investigate but according to quick google there are 2 formats. The legacy format which is lh-based and then the new one which is something different (no docs, no source). Files you linked are of the second variety.

I'll see if I can see the compressor code from either PowerPlayer or Octamed to see what it is made of

**Comment by temisu** [comment]
Well, suppoting these formats was easier than expected. But I take my wins where I can :)
