### ISSUE TITLE
Pack-Ice support

### ISSUE THREAD

**Issue by sagamusix** [temisu/ancient#72]
https://eab.abime.net/showpost.php?p=1617809&postcount=7

The decompression itself looks relatively simple to implement (apart from detecting the variants). It's mainly used on Atari I guess (I have seen a handful of modules packed with it that were shipped with Digital Tracker), but apparently it's also seen on Amiga.

Apart from the test files linked in the forum post, here's a packed module: https://ftp.modland.com/pub/software/trackers/Atari/Digital%20Tracker/digitaltracker1917.zip (MODULES/SOGOOD_D.DTM) - and lots of packed files here: https://sndh.atari.org/sndh/sndh_lf/

**Comment by temisu** [comment]
Pack-Ice is indeed next on my list. And yes, it has quite a lot of variants.

**Comment by temisu** [comment]
Well, that is one quirky format. Easily top-10. Got it finally working though

**Comment by sagamusix** [comment]
Thanks! Do you want to add the new magic bytes ("Ice!", "TMM!", "TSM!", "SHE!", "ICE!") to fuzzing/all_formats.dict or should I open a PR?

**Comment by temisu** [comment]
I did not add them. I'll add them myself by the next set of changes

**Comment by sagamusix** [comment]
Okay, in that case you may also want to add the new PMC magic bytes. I think there were also some new formats introduced since I first created the list of magic bytes for the fuzzer, so it's quite possible that there are some more missing entries in this list.
